export interface Question {
  text: string;
  options: string[];
  correct?: string;
}

export type BookData = Record<string, Question[]>;

export const BOOK_DATA: BookData = {
  "6": [
    { text: "1. Did Mary Lennox find a key in the robin's nest?", options: ["Yes", "No", "Not given"], correct: "No" },
    { text: "2. Was the secret garden locked?", options: ["Yes", "No", "Not given"], correct: "Yes" },
    { text: "3. Did Mary Lennox know who had the other key to the garden?", options: ["Yes", "No", "Not given"], correct: "Not given" },
    { text: "4. Did Mary Lennox open the door to the secret garden?", options: ["Yes", "No", "Not given"], correct: "No" },
    { text: "5. Was the secret garden beautiful?", options: ["Yes", "No", "Not given"], correct: "Not given" },

    { text: "6. What did Mary Lennox find in the robin's nest?\n\nA) A key\nB) A ring\nC) A bird", options: ["A", "B", "C"], correct: "A" },
    { text: "7. Who did Mary Lennox think had the other key to the secret garden?\n\nA) Martha\nB) Dickon\nC) Colin", options: ["A", "B", "C"], correct: "A" },
    { text: "8. What did Mary Lennox do when she found the key?\n\nA) She hid it\nB) She threw it away\nC) She tried to open the door to the secret garden", options: ["A", "B", "C"], correct: "A" },
    { text: "9. What did Mary Lennox see when she opened the door to the secret garden?\n\nA) A beautiful garden\nB) A dark and overgrown space\nC) Nothing", options: ["A", "B", "C"], correct: "B" },
    { text: "10. What did Mary Lennox decide to do with the secret garden?\n\nA) Keep it a secret\nB) Share it with her cousin Colin\nC) Lock it up again", options: ["A", "B", "C"], correct: "A" },

    { text: "11. Match: The robin\n\nA. A hidden key\nB. A curious child\nC. A locked door\nD. A hidden paradise\nE. A cheerful bird", options: ["A", "B", "C", "D", "E"], correct: "E" },
    { text: "12. Match: The secret garden\n\nA. A hidden key\nB. A curious child\nC. A locked door\nD. A hidden paradise\nE. A cheerful bird", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "13. Match: Mary Lennox\n\nA. A hidden key\nB. A curious child\nC. A locked door\nD. A hidden paradise\nE. A cheerful bird", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "14. Match: The key\n\nA. A hidden key\nB. A curious child\nC. A locked door\nD. A hidden paradise\nE. A cheerful bird", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "15. Match: The door\n\nA. A hidden key\nB. A curious child\nC. A locked door\nD. A hidden paradise\nE. A cheerful bird", options: ["A", "B", "C", "D", "E"], correct: "C" },
  ],
  "7": [
    { text: "1. Mary Lennox was determined to find the key to the secret garden...\n\nA. and she was sure she would find it.\nB. but she couldn't find it anywhere.\nC. so she decided to give up.\nD. and she knew that it must have the key.\nE. and she was so happy to finally see it.", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "2. She searched everywhere she could think of...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "3. Mary Lennox was starting to lose hope...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "4. But then she remembered the robin...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "5. Mary Lennox followed the robin to the secret garden...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "E" },

    { text: "6. Match Synonym: Determined\n\nA. Sure\nB. Place\nC. Give up\nD. Recalled\nE. Joyful", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "7. Match Synonym: Everywhere\n\nA. Sure\nB. Place\nC. Give up\nD. Recalled\nE. Joyful", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "8. Match Synonym: Lose hope\n\nA. Sure\nB. Place\nC. Give up\nD. Recalled\nE. Joyful", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "9. Match Synonym: Remembered\n\nA. Sure\nB. Place\nC. Give up\nD. Recalled\nE. Joyful", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "10. Match Synonym: Happy\n\nA. Sure\nB. Place\nC. Give up\nD. Recalled\nE. Joyful", options: ["A", "B", "C", "D", "E"], correct: "E" },

    { text: "11. Match Antonym: Determined\n\nA. Unsure\nB. Nowhere\nC. Gain hope\nD. Forgot\nE. Sad", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "12. Match Antonym: Everywhere\n\nA. Unsure\nB. Nowhere\nC. Gain hope\nD. Forgot\nE. Sad", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "13. Match Antonym: Lose hope\n\nA. Unsure\nB. Nowhere\nC. Gain hope\nD. Forgot\nE. Sad", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "14. Match Antonym: Remembered\n\nA. Unsure\nB. Nowhere\nC. Gain hope\nD. Forgot\nE. Sad", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "15. Match Antonym: Happy\n\nA. Unsure\nB. Nowhere\nC. Gain hope\nD. Forgot\nE. Sad", options: ["A", "B", "C", "D", "E"], correct: "E" },
  ],
  "8": [
    { text: "1. Mary Lennox was afraid of the robin.", options: ["True", "False", "Not Given"], correct: "False" },
    { text: "2. The secret garden was full of beautiful flowers.", options: ["True", "False", "Not Given"], correct: "False" },
    { text: "3. Mary Lennox met a boy named Dickon in the garden.", options: ["True", "False", "Not Given"], correct: "False" },
    { text: "4. Dickon was afraid of animals.", options: ["True", "False", "Not Given"], correct: "False" },
    { text: "5. Mary Lennox and Dickon became good friends.", options: ["True", "False", "Not Given"], correct: "False" },

    { text: "6. What did Mary Lennox find in the robin's nest?\n\nA) A key\nB) A ring\nC) A bird", options: ["A", "B", "C"], correct: "A" },
    { text: "7. Who did Mary Lennox think had the other key to the secret garden?\n\nA) Martha\nB) Dickon\nC) Colin", options: ["A", "B", "C"], correct: "A" },
    { text: "8. What did Mary Lennox do when she found the key?\n\nA) She hid it\nB) She threw it away\nC) She tried to open the door to the secret garden", options: ["A", "B", "C"], correct: "A" },
    { text: "9. What did Mary Lennox see when she opened the door to the secret garden?\n\nA) A beautiful garden\nB) A dark and overgrown space\nC) Nothing", options: ["A", "B", "C"], correct: "B" },
    { text: "10. What did Mary Lennox decide to do with the secret garden?\n\nA) Keep it a secret\nB) Share it with her cousin Colin\nC) Lock it up again", options: ["A", "B", "C"], correct: "A" },

    { text: "11. Match Antonym: Open\n\nA. Closed\nB. Ugly\nC. Large\nD. Sad\nE. Night", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "12. Match Antonym: Beautiful\n\nA. Closed\nB. Ugly\nC. Large\nD. Sad\nE. Night", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "13. Match Antonym: Small\n\nA. Closed\nB. Ugly\nC. Large\nD. Sad\nE. Night", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "14. Match Antonym: Happy\n\nA. Closed\nB. Ugly\nC. Large\nD. Sad\nE. Night", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "15. Match Antonym: Day\n\nA. Closed\nB. Ugly\nC. Large\nD. Sad\nE. Night", options: ["A", "B", "C", "D", "E"], correct: "E" },
  ],
  "9": [
    { text: "1. Mary Lennox was surprised to learn that...\n\nA. was actually quite kind and gentle.\nB. had always been kept shut up in his room.\nC. the robin had built its nest there.\nD. he had a secret garden of his own.\nE. was a kind and loving man.", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "2. Dickon told Mary that his mother...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "3. Colin Craven was afraid to go outside because...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "4. Mary and Dickon discovered a hidden door in...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "5. Colin's father...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "E" },

    { text: "6. Match Synonym: Curious\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "7. Match Synonym: Gentle\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "8. Match Synonym: Afraid\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "9. Match Synonym: Discovered\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "10. Match Synonym: Secret\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "E" },

    { text: "11. Mary Lennox was happy to learn that Colin Craven was afraid to go outside.", options: ["True", "False", "Not Given"], correct: "False" },
    { text: "12. Dickon's mother was a kind and loving woman.", options: ["True", "False", "Not Given"], correct: "True" },
    { text: "13. Colin Craven's father was a cruel and heartless man.", options: ["True", "False", "Not Given"], correct: "Not Given" },
    { text: "14. Mary and Dickon found a hidden door in the robin's nest.", options: ["True", "False", "Not Given"], correct: "False" },
    { text: "15. Colin Craven was excited to explore the secret garden with Mary and Dickon.", options: ["True", "False", "Not Given"], correct: "True" },
  ],
  "10": [
    { text: "1. Mary Lennox was surprised to see that Colin Craven was not as ___ as she had imagined.\n\n(Type your answer in the chat or think about it, then press Continue)", options: ["Continue \u27a1\ufe0f"] },
    { text: "2. Dickon told Mary that the secret garden was a ___ place where anything was possible.", options: ["Continue \u27a1\ufe0f"] },
    { text: "3. Colin Craven was ___ to go outside for the first time in years.", options: ["Continue \u27a1\ufe0f"] },
    { text: "4. Mary and Dickon helped Colin to ___ in the garden, and he began to grow stronger and healthier.", options: ["Continue \u27a1\ufe0f"] },
    { text: "5. The secret garden became a ___ place for all three children", options: ["Continue \u27a1\ufe0f"] },

    { text: "6. Mary Lennox was surprised to learn that...\n\nA. was actually quite kind and gentle.\nB. had always been kept shut up in his room.\nC. the robin had built its nest there.\nD. he had a secret garden of his own.\nE. was a kind and loving man.", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "7. Dickon told Mary that his mother...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "8. Colin Craven was afraid to go outside because...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "9. Mary and Dickon discovered a hidden door in...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "10. Colin's father...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "E" },

    { text: "11. Match Synonym: Curious\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "12. Match Synonym: Gentle\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "13. Match Synonym: Afraid\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "14. Match Synonym: Discovered\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "15. Match Synonym: Secret\n\nA. Afraid\nB. Kind\nC. Surprised\nD. Found\nE. Hidden", options: ["A", "B", "C", "D", "E"], correct: "E" },
  ],
  "11": [
    { text: "1. Mary Lennox was happy to learn that Colin Craven was afraid to go outside.", options: ["Yes", "No", "Not Given"], correct: "No" },
    { text: "2. Dickon's mother was a kind and loving woman.", options: ["Yes", "No", "Not Given"], correct: "Yes" },
    { text: "3. Colin Craven's father was a cruel and heartless man.", options: ["Yes", "No", "Not Given"], correct: "Not Given" },
    { text: "4. Mary and Dickon found a hidden door in the robin's nest.", options: ["Yes", "No", "Not Given"], correct: "No" },
    { text: "5. Colin Craven was excited to explore the secret garden with Mary and Dickon.", options: ["Yes", "No", "Not Given"], correct: "Yes" },

    { text: "6. Mary Lennox was surprised to see that Colin Craven...\n\nA. was actually quite kind and gentle.\nB. had always been kept shut up in his room.\nC. the robin had built its nest there.\nD. he had a secret garden of his own.\nE. was a kind and loving man.", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "7. Dickon told Mary that his mother...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "8. Colin Craven was afraid to go outside because...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "9. Mary and Dickon discovered a hidden door in...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "10. Colin's father...\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "E" },

    { text: "11. Match Antonym: Happy\n\nA. Sad\nB. Weak\nC. Ugly\nD. Sickly\nE. Calm", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "12. Match Antonym: Strong\n\nA. Sad\nB. Weak\nC. Ugly\nD. Sickly\nE. Calm", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "13. Match Antonym: Beautiful\n\nA. Sad\nB. Weak\nC. Ugly\nD. Sickly\nE. Calm", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "14. Match Antonym: Healthy\n\nA. Sad\nB. Weak\nC. Ugly\nD. Sickly\nE. Calm", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "15. Match Antonym: Excited\n\nA. Sad\nB. Weak\nC. Ugly\nD. Sickly\nE. Calm", options: ["A", "B", "C", "D", "E"], correct: "E" },
  ],
  "12": [
    { text: "1. Mary and Colin decide to keep the secret garden a secret from everyone else.", options: ["True", "False"], correct: "False" },
    { text: "2. Colin's father is initially skeptical of his son's recovery.", options: ["True", "False"], correct: "False" },
    { text: "3. Mary discovers a robin's nest in the secret garden.", options: ["True", "False"], correct: "False" },
    { text: "4. Colin is afraid to walk on his own.", options: ["True", "False"], correct: "False" },
    { text: "5. Mary and Colin become close friends.", options: ["True", "False"], correct: "False" },

    { text: "6. What does Mary discover in the secret garden that makes her happy?\n\nA) A new doll\nB) A robin's nest\nC) A hidden treasure\nD) A beautiful flower", options: ["A", "B", "C", "D"], correct: "B" },
    { text: "7. Who is skeptical of Colin's recovery at first?\n\nA) Mary\nB) Dickon\nC) Colin's father\nD) Mrs. Medlock", options: ["A", "B", "C", "D"], correct: "C" },
    { text: "8. What does Colin ask Mary to do for him?\n\nA) Help him walk\nB) Read to him\nC) Play games with him\nD) Keep the secret garden a secret", options: ["A", "B", "C", "D"], correct: "D" },
    { text: "9. What do Mary and Colin do together in the secret garden?\n\nA) Play hide-and-seek\nB) Plant flowers\nC) Eat picnics\nD) All of the above", options: ["A", "B", "C", "D"], correct: "B" },
    { text: "10. How does Colin's health improve over time?\n\nA) He becomes stronger and more active.\nB) He starts to gain weight.\nC) His eyesight improves.\nD) All of the above", options: ["A", "B", "C", "D"], correct: "A" },

    { text: "11. Match: A kind-hearted boy who loves animals", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "12. Match: A young girl who discovers a secret garden", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "13. Match: A sickly boy who is confined to his bed", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "14. Match: A robin's nest", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "15. Match: A hidden garden full of flowers", options: ["A", "B", "C", "D", "E"], correct: "E" },

    { text: "16. Mary discovers a hidden door in the garden wall.", options: ["Yes", "No", "Not Given"], correct: "No" },
    { text: "17. Colin is initially afraid to go outside.", options: ["Yes", "No", "Not Given"], correct: "Not Given" },
    { text: "18. Mary and Colin become best friends.", options: ["Yes", "No", "Not Given"], correct: "Not Given" },
    { text: "19. Dickon brings animals into the secret garden.", options: ["Yes", "No", "Not Given"], correct: "Not Given" },
    { text: "20. Colin's father is a kind and loving man.", options: ["Yes", "No", "Not Given"], correct: "Not Given" },

    { text: "21. Open Question:\nWhat does Mary discover in the secret garden that makes her happy?\n\n(Think about your answer or type it in chat, then press Continue)", options: ["Continue \u27a1\ufe0f"] },
    { text: "22. Open Question:\nWhy is Colin initially afraid to go outside?", options: ["Continue \u27a1\ufe0f"] },
    { text: "23. Open Question:\nHow does Mary help Colin to overcome his fear?", options: ["Continue \u27a1\ufe0f"] },
    { text: "24. Open Question:\nWhat do Mary and Colin do together in the secret garden?", options: ["Continue \u27a1\ufe0f"] },
    { text: "25. Open Question:\nHow does Colin's health improve over time?", options: ["Continue \u27a1\ufe0f"] },
  ],
  "13": [
    { text: "1. Match Synonym: radiant\n\nA. beautiful\nB. recovering\nC. tired\nD. boring\nE. glowing", options: ["A", "B", "C", "D", "E"], correct: "E" },
    { text: "2. Match Synonym: convalescent\n\nA. beautiful\nB. recovering\nC. tired\nD. boring\nE. glowing", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "3. Match Synonym: exhilarated\n\nA. beautiful\nB. recovering\nC. tired\nD. boring\nE. glowing", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "4. Match Synonym: monotonous\n\nA. beautiful\nB. recovering\nC. tired\nD. boring\nE. glowing", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "5. Match Synonym: rejuvenated\n\nA. beautiful\nB. recovering\nC. tired\nD. boring\nE. glowing", options: ["A", "B", "C", "D", "E"], correct: "A" },

    { text: "6. Match Definition: convalescent\n\nA. very happy and excited\nB. gradually getting better from an illness\nD. always the same and boring\nE. made to feel young and healthy again", options: ["A", "B", "D", "E"], correct: "B" },
    { text: "7. Match Definition: exhilarated\n\nA. very happy and excited\nB. gradually getting better from an illness\nD. always the same and boring\nE. made to feel young and healthy again", options: ["A", "B", "D", "E"], correct: "A" },
    { text: "8. Match Definition: monotonous\n\nA. very happy and excited\nB. gradually getting better from an illness\nD. always the same and boring\nE. made to feel young and healthy again", options: ["A", "B", "D", "E"], correct: "D" },
    { text: "9. Match Definition: rejuvenated\n\nA. very happy and excited\nB. gradually getting better from an illness\nD. always the same and boring\nE. made to feel young and healthy again", options: ["A", "B", "D", "E"], correct: "E" },

    { text: "10. What does Mary notice about Colin's appearance when she sees him again after a few weeks?\n\nA) He is looking healthier and stronger.\nB) He is still very pale and weak.\nC) He has grown taller.\nD) He has a new haircut.", options: ["A", "B", "C", "D"], correct: "A" },
    { text: "11. What does Colin ask Mary to do for him?\n\nA) Help him walk\nB) Read to him\nC) Play games with him\nD) Keep the secret garden a secret", options: ["A", "B", "C", "D"], correct: "D" },
    { text: "12. What do Mary and Colin do together in the secret garden?\n\nA) Play hide-and-seek\nB) Plant flowers\nC) Eat picnics\nD) All of the above", options: ["A", "B", "C", "D"], correct: "D" },
    { text: "13. How does Colin's health continue to improve?\n\nA) He starts to gain weight.\nB) He becomes more active and energetic.\nC) His eyesight improves.\nD) All of the above", options: ["A", "B", "C", "D"], correct: "D" },
    { text: "14. What does the doctor say about Colin's progress?\n\nA) He is making remarkable progress.\nB) He is not improving as quickly as expected.\nC) He needs to rest more.\nD) He should be sent to a different doctor.", options: ["A", "B", "C", "D"], correct: "A" },

    { text: "15. Mary is surprised to see how much Colin has improved when she sees him again after a few weeks.", options: ["True", "False"], correct: "False" },
    { text: "16. Colin is still afraid to walk on his own.", options: ["True", "False"], correct: "True" },
    { text: "17. Mary and Colin spend every day together in the secret garden.", options: ["True", "False"], correct: "False" },
    { text: "18. Colin's father is happy to see how much progress Colin is making.", options: ["True", "False"], correct: "False" },
    { text: "19. The doctor tells Mary that Colin is not getting any better.", options: ["True", "False"], correct: "False" },

    { text: "20. Match Antonym: weak\n\nA. strong\nB. sad\nC. ugly\nD. lazy\nE. sick", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "21. Match Antonym: happy\n\nA. strong\nB. sad\nC. ugly\nD. lazy\nE. sick", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "22. Match Antonym: beautiful\n\nA. strong\nB. sad\nC. ugly\nD. lazy\nE. sick", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "23. Match Antonym: active\n\nA. strong\nB. sad\nC. ugly\nD. lazy\nE. sick", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "24. Match Antonym: healthy\n\nA. strong\nB. sad\nC. ugly\nD. lazy\nE. sick", options: ["A", "B", "C", "D", "E"], correct: "E" },
  ],
  "14": [
    { text: "1. Open Question:\nWhat does Mary discover about Colin's past?", options: ["Continue \u27a1\ufe0f"] },
    { text: "2. Open Question:\nWhy is Colin so angry and resentful?", options: ["Continue \u27a1\ufe0f"] },
    { text: "3. Open Question:\nHow does Mary help Colin to overcome his anger and resentment?", options: ["Continue \u27a1\ufe0f"] },
    { text: "4. Open Question:\nWhat does Colin realize about his father?", options: ["Continue \u27a1\ufe0f"] },
    { text: "5. Open Question:\nHow does Colin's relationship with his father change?", options: ["Continue \u27a1\ufe0f"] },

    { text: "6. Did Mary have any friends before she came to Misselthwaite Manor?", options: ["Yes", "No", "Not Given"], correct: "No" },
    { text: "7. Was Martha's brother a gardener?", options: ["Yes", "No", "Not Given"], correct: "No" },
    { text: "8. Did Mary discover a secret garden hidden in the manor's grounds?", options: ["Yes", "No", "Not Given"], correct: "Yes" },
    { text: "9. Was Ben Weatherstaff a kind and cheerful old man?", options: ["Yes", "No", "Not Given"], correct: "No" },
    { text: "10. Did Mary befriend a robin redbreast?", options: ["Yes", "No", "Not Given"], correct: "Yes" },

    { text: "11. Match: 'It was the sweetest, most mysterious-looking place anyone could imagine.'\n\nA. Mary's description of the secret garden\nB. Colin's transformation after spending time in the secret garden\nC. Mary's first glimpse of the secret garden\nD. Mary's discovery of the hidden door\nE. The appearance of the secret garden", options: ["A", "B", "C", "D", "E"], correct: "A" },
    { text: "12. Match: 'The sun was shining on it and everything was green and full of lovely flowers.'\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "E" },
    { text: "13. Match: 'He had been a fretful, peevish boy, but his fretfulness and peevishness had passed away.'\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "14. Match: 'When she had run as hard as she could, she suddenly stopped.'\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "15. Match: 'She put up her hands to push the door open and looked eagerly in.'\n\n[Same options A-E]", options: ["A", "B", "C", "D", "E"], correct: "D" },

    { text: "16. Mary discovers the secret garden on her first day at Misselthwaite Manor.", options: ["True", "False"], correct: "False" },
    { text: "17. Ben Weatherstaff is initially friendly towards Mary.", options: ["True", "False"], correct: "False" },
    { text: "18. Colin Craven is confined to his bed due to a hunchback.", options: ["True", "False"], correct: "False" },
    { text: "19. Mary befriends a robin redbreast named Cock Robin.", options: ["True", "False"], correct: "False" },
    { text: "20. The secret garden is full of vibrant and colorful flowers.", options: ["True", "False"], correct: "False" },

    { text: "21. What is the name of the main character in 'The Secret Garden'?\n\nA) Mary Lennox\nB) Colin Craven\nC) Dickon Sowerby\nD) Archibald Craven", options: ["A", "B", "C", "D"], correct: "A" },
    { text: "22. Where is 'The Secret Garden' located on the estate?\n\nA) Behind the manor house\nB) In the woods\nC) Near the river\nD) In the greenhouse", options: ["A", "B", "C", "D"], correct: "A" },
    { text: "23. Who helps Mary discover the secret garden?\n\nA) Martha\nB) Ben Weatherstaff\nC) Dickon\nD) Mrs. Medlock", options: ["A", "B", "C", "D"], correct: "B" },
    { text: "24. Why is Colin kept hidden away in the manor?\n\nA) He is sickly and weak\nB) He is afraid of the outside world\nC) He is spoiled and disobedient\nD) He is a secret prince", options: ["A", "B", "C", "D"], correct: "A" },
    { text: "25. How does the secret garden change Mary, Colin, and Dickon's lives?\n\nA) They become wealthy and famous\nB) They learn to appreciate nature and friendship\nC) They uncover a hidden treasure\nD) They solve a mystery in the manor house", options: ["A", "B", "C", "D"], correct: "B" },
  ],
  "15": [
    { text: "1. Mary discovers a hidden key in the garden.", options: ["True", "False", "Not given"], correct: "False" },
    { text: "2. Dickon helps Mary unlock the door to the secret garden.", options: ["True", "False", "Not given"], correct: "False" },
    { text: "3. The secret garden is filled with beautiful flowers and plants.", options: ["True", "False", "Not given"], correct: "False" },
    { text: "4. Mary decides to keep the secret garden all to herself.", options: ["True", "False", "Not given"], correct: "False" },
    { text: "5. Colin is initially hesitant to enter the secret garden.", options: ["True", "False", "Not given"], correct: "Not given" },

    { text: "6. What does Mary find in the secret garden that surprises her?\n\nA) A hidden door\nB) A statue of a boy\nC) A key to unlock another door\nD) A note from her uncle", options: ["A", "B", "C", "D"], correct: "A" },
    { text: "7. How does Mary feel about the garden after discovering its secrets?\n\nA) Excited and hopeful\nB) Anxious and scared\nC) Indifferent and bored\nD) Angry and frustrated", options: ["A", "B", "C", "D"], correct: "A" },
    { text: "8. Who does Mary decide to share the secret garden with?\n\nA) Martha and Dickon\nB) Colin and Ben Weatherstaff\nC) Mrs. Medlock and Dr. Craven\nD) The robin and other animals", options: ["A", "B", "C", "D"], correct: "B" },
    { text: "9. What does Mary learn about the power of nature and friendship in the secret garden?\n\nA) They can heal and bring joy\nB) They are dangerous and unpredictable\nC) They are best kept separate\nD) They have no impact on her life", options: ["A", "B", "C", "D"], correct: "A" },
    { text: "10. How does Mary's relationship with Colin change after they both experience the magic of the secret garden?\n\nA) They become closer and more understanding\nB) They drift apart and stop talking\nC) They argue and fight over the garden\nD) They decide to keep the garden a secret from everyone", options: ["A", "B", "C", "D"], correct: "A" },

    { text: "11. Mary discovers a hidden door in the wall of the garden.", options: ["Yes", "No", "Not given"], correct: "Yes" },
    { text: "12. Ben Weatherstaff helps Mary find the key to the hidden door.", options: ["Yes", "No", "Not given"], correct: "No" },
    { text: "13. Mary enters the secret garden alone for the first time.", options: ["Yes", "No", "Not given"], correct: "Yes" },
    { text: "14. Mary meets Colin for the first time in the secret garden.", options: ["Yes", "No", "Not given"], correct: "No" },
    { text: "15. The secret garden is described as a barren and desolate place.", options: ["Yes", "No", "Not given"], correct: "No" },
  ],
  "16": [
    { text: "1. Did Colin Craven's parents die when he was a child?", options: ["Yes", "No", "Not given"], correct: "No" },
    { text: "2. Was Martha Sowerby a kind and loving nurse to Colin?", options: ["Yes", "No", "Not given"], correct: "No" },
    { text: "3. Did Colin Craven have a fear of being outdoors?", options: ["Yes", "No", "Not given"], correct: "Yes" },
    { text: "4. Did Mary Lennox believe that the secret garden was real?", options: ["Yes", "No", "Not given"], correct: "Yes" },
    { text: "5. Did Colin Craven's cousin, Dickon Sowerby, live on the estate?", options: ["Yes", "No", "Not given"], correct: "No" },

    { text: "6. Match Antonym: kind\n\nA. hatred\nB. outside\nC. joyful\nD. unkind\nE. strong", options: ["A", "B", "C", "D", "E"], correct: "D" },
    { text: "7. Match Antonym: inside\n\nA. hatred\nB. outside\nC. joyful\nD. unkind\nE. strong", options: ["A", "B", "C", "D", "E"], correct: "B" },
    { text: "8. Match Antonym: weak\n\nA. hatred\nB. outside\nC. joyful\nD. unkind\nE. strong", options: ["A", "B", "C", "D", "E"], correct: "E" },
    { text: "9. Match Antonym: sad\n\nA. hatred\nB. outside\nC. joyful\nD. unkind\nE. strong", options: ["A", "B", "C", "D", "E"], correct: "C" },
    { text: "10. Match Antonym: love\n\nA. hatred\nB. outside\nC. joyful\nD. unkind\nE. strong", options: ["A", "B", "C", "D", "E"], correct: "A" },

    { text: "11. What did Mary Lennox discover in the robin's nest?\n\nA) A broken egg\nB) A gold ring\nC) A key", options: ["A", "B", "C"], correct: "C" },
    { text: "12. Who did Mary Lennox meet in the garden?\n\nA) Dickon Sowerby\nB) Colin Craven\nC) Martha Sowerby", options: ["A", "B", "C"], correct: "A" },
    { text: "13. What did Colin Craven suffer from?\n\nA) A broken leg\nB) A heart condition\nC) A fear of being outdoors", options: ["A", "B", "C"], correct: "C" },
    { text: "14. What did Mary Lennox and Dickon Sowerby do together in the garden?\n\nA) Played games\nB) Planted flowers\nC) Read books", options: ["A", "B", "C"], correct: "B" },
    { text: "15. What did Colin Craven call the secret garden?\n\nA) My paradise\nB) My sanctuary\nC) My kingdom", options: ["A", "B", "C"], correct: "A" },
  ],
};
